= TeXification of "Gödel, Escher, Bach"
:hide-uri-scheme:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://github.com/Lipen/godel-escher-bach/actions/workflows/build.yml/badge.svg?branch=master["Build",link="https://github.com/Lipen/godel-escher-bach/actions/workflows/build.yml"]
image:https://img.shields.io/badge/PDF-preview-blue?style=social&logo=gitbook["PDF",link="https://lipen.github.io/godel-escher-bach/main.pdf"]

:fn-rus: footnote:[Д.Р. Хофштадтер "Гёдель, Эшер, Бах: эта бесконечная гирлянда".]
> This repository contains a $\TeX$ reproduction of the Russian translation{fn-rus} of the link:https://en.wikipedia.org/wiki/Godel,_Escher,_Bach[book] "Gödel, Escher, Bach: An Eternal Golden Braid" by link:https://en.wikipedia.org/wiki/Douglas_Hofstadter[Douglas Hofstadter].


== Download

[source]
----
git clone https://github.com/Lipen/godel-escher-bach
cd godel-escher-bach
----

NOTE: You may want to use `git lfs pull` (see link:https://git-lfs.github.com[Git LFS]) in order to download all images (and probably other large files). However, modern Git should automatically do this for you (while `git clone`), so you don't have to.


== Build

To compile the PDF from the source code, you have two options:

1. Using link:https://mg.readthedocs.io/latexmk.html[Latexmk] (a Perl script for running LaTeX the correct number of times to resolve cross-references, etc.):
+
[source]
----
latexmk -pdf main.tex
----

2. Using link:https://tectonic-typesetting.github.io[Tectonic] (a modernized, complete, self-contained TeX/LaTeX engine):
+
[source]
----
tectonic main.tex
----


== Work in progress

image:https://progress-bar.dev/40/?title=Progress[link="progress.adoc"] (link:progress.adoc[click for details])

See link:CONTRIBUTING.md[] if you wanna help!

- [x] Transform raw sources into TeX
- [x] Fix artefacts (typos, missing/unnecessary spaces, etc)
- [x] Format dialogues
- [ ] Format text blocks
- [ ] Format math formulae
- [ ] Format tables
- [x] Format chapters/sections
- [ ] Implement diagrams using TikZ
- [ ] Add illustrations
- [x] Add glossary
- [ ] Add bibliography
- [ ] Create fancy page design


== Credits

* The source text in DOC format was taken from link:https://royallib.com[RoyalLib].
* DOC sources were converted to LaTeX using link:https://pandoc.org[`pandoc`] utility.
* Illustrations were mostly found online, or screenshoted from the original ebook.
* Escher's drawings were taken from link:https://www.wikiart.org/en/m-c-escher/all-works/text-list[WikiArt].
* Some illustrations were automagically upscaled and colorized using Photoshop.
